### ISSUE TITLE
trying to link lp bug to an Epic fails with "Public API does not support this request" 

### ISSUE THREAD

**Issue by bladernr** [canonical/lp-to-jira#17]
Ran into this while trying to convert an LP bug to a Jira issue and linking it to an Epic on a company-managed project.

bladernr@galactica:~/development/$ lp-to-jira -E MYPROJECT-160 -l 22.04 1873936 MYPROJECT
Exception ignored in: <function Magic.del at 0x7fd0ff272ca0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/magic/init.py", line 125, in del
    if self.cookie and magic_close:
AttributeError: 'Magic' object has no attribute 'cookie'
Created https://jira-service-url/browse/MYPROJECT-197
Traceback (most recent call last):
  File "/usr/local/bin/lp-to-jira", line 11, in <module>
    load_entry_point('LpToJira==0.7', 'console_scripts', 'lp-to-jira')()
  File "/usr/local/lib/python3.8/dist-packages/LpToJira-0.7-py3.8.egg/LpToJira/lp_to_jira.py", line 318, in main
  File "/usr/local/lib/python3.8/dist-packages/LpToJira-0.7-py3.8.egg/LpToJira/lp_to_jira.py", line 183, in lp_to_jira_bug
  File "/usr/local/lib/python3.8/dist-packages/LpToJira-0.7-py3.8.egg/LpToJira/lp_to_jira.py", line 164, in create_jira_issue
  File "/usr/local/lib/python3.8/dist-packages/jira-3.1.1-py3.8.egg/jira/client.py", line 4768, in add_issues_to_epic
    raise NotImplementedError(
NotImplementedError: Jira Agile Public API does not support this request

**Comment by mclemenceau** [comment]
Tried today with the latest snap on a sandbox jira project and it worked without a problem,
Can you tell me what version of the snap you have as well as what version of the jira python plugin if you have one on the system? pip list | grep jira
It could be specific to your JIRA project which could be different than mine.

**Comment by bladernr** [comment]
I didn't mean to close it... sorry...
I think maybe at least there needs to be some installation instructions to be sure someone doing what I did initially knows to pip install jira, and install any other dependencies...  I'd be interested in tracking down where these came from... I have this:
/usr/local/lib/python3.8/dist-packages/jira-3.1.1-py3.8.egg/jira

which is the only python library I can find for Jira, but I didn't install it explicitly so I'm guessing setup.py did.
