### ISSUE TITLE
JiraError HTTP 400 url: https://warthogs.atlassian.net/rest/api/2/issue         text: Could not find valid 'id' or 'name' in component object.

### ISSUE THREAD

**Issue by julian-klode** [canonical/lp-to-jira#32]
```
$ lp-to-jira 1842320 FR
Traceback (most recent call last):
  File "/snap/lp-to-jira/54/bin/lp-to-jira", line 8, in <module>
    sys.exit(main())
  File "/snap/lp-to-jira/54/lib/python3.8/site-packages/LpToJira/lp_to_jira.py", line 344, in main
    lp_to_jira_bug(lp, jira, bug, project_id, opts)
  File "/snap/lp-to-jira/54/lib/python3.8/site-packages/LpToJira/lp_to_jira.py", line 185, in lp_to_jira_bug
    jira_issue = create_jira_issue(jira, issue_dict, bug, opts)
  File "/snap/lp-to-jira/54/lib/python3.8/site-packages/LpToJira/lp_to_jira.py", line 156, in create_jira_issue
    new_issue = jira.create_issue(fields=issue_dict)
  File "/snap/lp-to-jira/54/lib/python3.8/site-packages/jira/client.py", line 1315, in create_issue
    r = self._session.post(url, data=json.dumps(data))
  File "/snap/lp-to-jira/54/lib/python3.8/site-packages/jira/resilientsession.py", line 175, in post
    return self.__verb("POST", url, **kwargs)
  File "/snap/lp-to-jira/54/lib/python3.8/site-packages/jira/resilientsession.py", line 168, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/snap/lp-to-jira/54/lib/python3.8/site-packages/jira/resilientsession.py", line 53, in raise_on_error
    raise JIRAError(
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://warthogs.atlassian.net/rest/api/2/issue
        text: Could not find valid 'id' or 'name' in component object.

        response headers = {'Date': 'Tue, 18 Oct 2022 14:07:18 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Server': 'globaledge-envoy', 'Timing-Allow-Origin': '*', 'X-Arequestid': '23710c1659958551f5ed01e8468d9046', 'X-Aaccountid': '5f3cf15fd0884f0049aa8c47', 'Cache-Control': 'no-cache, no-store, no-transform', 'X-Envoy-Upstream-Service-Time': '518', 'Expect-Ct': 'report-uri="https://web-security-reports.services.atlassian.com/expect-ct-report/atlassian-proxy", max-age=86400', 'Strict-Transport-Security': 'max-age=63072000; preload', 'X-Content-Type-Options': 'nosniff', 'X-Xss-Protection': '1; mode=block', 'Atl-Traceid': 'a926aec93a2189af', 'Report-To': '{"endpoints": [{"url": "https://dz8aopenkvv6s.cloudfront.net"}], "group": "endpoint-1", "include_subdomains": true, "max_age": 600}', 'Nel': '{"failure_fraction": 0.001, "include_subdomains": true, "max_age": 600, "report_to": "endpoint-1"}', 'Transfer-Encoding': 'chunked'}
        response text = {"errorMessages":[],"errors":{"components":"Could not find valid 'id' or 'name' in component object."}}
```

**Comment by mclemenceau** [comment]
There was an issue while there wasn't component specified and the package wasn't known. This is resolved with the latest commit (5d41295581f773bc93aaf78cb4581a6f05ab0bb3)
